import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import "./globals.css";
import Link from "next/link";
import { SignOutButton } from "@/components/sign-out-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed top-0 right-0 p-4 flex gap-4 items-center">
          {session ? (
            <>
              <span>Welcome, {session.user.name}</span>
              <SignOutButton />
            </>
          ) : (
            <>
              <Link href="/auth" className="text-blue-500 hover:underline">
                Sign in
              </Link>
              <Link href="/auth" className="text-blue-500 hover:underline">
                Sign up
              </Link>
            </>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
