import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { Sidebar } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionResponse = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en" className="h-full overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  h-full overflow-hidden`}
      >
        <SiteHeader session={sessionResponse?.session || null} />
        <div className="flex h-[calc(100vh-3.5rem)] overflow-hidden">
          <Sidebar />
          <main className="flex-1 p-4 h-full overflow-hidden w-full justify-center items-center">{children}</main>
        </div>
      </body>
    </html>
  );
  
}
